name: style_random
description: Random string generator with easy syntax and many complex options. Specify random string by character classes, define length, order by classes, add conditions like starting with, ending with or duplication.
version: 0.0.1
homepage: https://github.com/styledart/style_random
repository: https://github.com/styledart/style_random

environment:
  sdk: '>=2.15.0 <3.0.0'


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
